#ifndef CAN_CONTROLLER_CONFIGURATION_H_
#define CAN_CONTROLLER_CONFIGURATION_H_

#define CONTROLLER_DEVICE mcp2515

// #define CONTROLLER_PLATFORM_RASPBERRY_PI
#define CONTROLLER_PLATFORM_PSOC4

#endif  // CAN_CONTROLLER_CONFIGURATION_H_